#version 460 core
uniform vec3 camPos;
uniform vec3 camRight;
uniform vec3 camUp;
uniform vec3 camDir;

uniform float WIDTH;
uniform float HEIGHT;

uniform int STEPS;
#define steps 300
struct Ray {
	vec3 pos;
	vec3 dir;
};

struct RayPath {
	vec3 pos[steps];
	vec3 dir[steps];
};

layout(local_size_x = 1) in;
layout(std430, binding = 0) buffer RayPathBuffer {
	RayPath rayPaths[];
};

float sqMag(vec3 v) {
	return v.x*v.x + v.y*v.y + v.z*v.z;
}

float sqMag(vec2 v) {
	return v.x*v.x + v.y*v.y;
}

vec3 acceleration (float h2, vec3 pos) {
	//this does not describe the real motion of the photon, but it does give an equivalent trajectory.
	float r5 = pow(sqMag(pos), 2.5);
	return -1.5*h2*pos/r5;
	
}

vec3 acc(float h2, vec3 pos) {
	float r5 = pow(sqMag(pos), 2.5);
	return -1.5*h2*pos/r5;
}

Ray rungekutta(float h2, Ray ray, float h) {
	vec3 k1, k2, k3, k4, l1, l2, l3, l4;

	k1 = ray.dir;
	l1 = acc(h2, ray.pos);

	k2 = ray.dir + h*0.5*l1;
	l2 = acc(h2, h*0.5*k1+ray.pos);

	k3 = ray.dir + h*0.5*l2;
	l3 = acc(h2, h*0.5*k2+ray.pos);

	k4 = ray.dir + h*l3;
	l4 = acc(h2, h*k3+ray.pos);

	return Ray(ray.pos+h/6*(k1+2*k2+2*k3+k4), ray.dir+h/6*(l1+2*l2+2*l3+l4));
	
}


void main() {
	uint index = gl_GlobalInvocationID.x;

	
	Ray ray = Ray(camPos, camDir);
	float fov = 90.0;
	float x = float(index)/WIDTH -0.5;
	x*= 2*WIDTH/HEIGHT;
	float y = 0;

	ray.dir = normalize(mat3(camRight, camUp, camDir) * vec3(x, y, 1));
	Ray prevRay = ray;
	rayPaths[index].pos[0] = ray.pos;
	rayPaths[index].dir[0] = ray.dir;
	float h2 = sqMag(cross(ray.pos, ray.dir));
	float dt = float(40)/steps;//higher means less accurate, but further

	for (int i = 1; i < steps; i++) {
		prevRay = ray;
		ray=rungekutta(h2, prevRay, dt);
		if (sqMag(ray.pos)<=1) {//inside event horizon
			for (int j = i; j < steps; j++) {
				rayPaths[index].pos[j] = vec3(0);
				rayPaths[index].dir[j] = vec3(0);
				
			}
			return;
		}

		rayPaths[index].pos[i] = ray.pos;
		rayPaths[index].dir[i] = ray.dir;
		
				

		
	}
}

