#version 460 core
uniform vec3 camPos;
uniform vec3 camRight;
uniform vec3 camUp;
uniform vec3 camDir;

uniform float WIDTH;
uniform float HEIGHT;
uniform int TOTALCALLS;
uniform int STEPS;
#define steps 300
#define PI 3.14159265359
struct Ray {
	vec3 pos;
	vec3 dir;
};

struct RayPath {
	vec3 pos[steps];
	vec3 dir[steps];
};

layout(local_size_x = 64) in;
layout(std430, binding = 0) buffer RayPathBuffer {
	RayPath rayPaths[];
};

float sqMag(vec3 v) {
	return v.x*v.x + v.y*v.y + v.z*v.z;
}

float sqMag(vec2 v) {
	return v.x*v.x + v.y*v.y;
}

//quaternions
//real part as 4th element
vec4 quatConjugate(vec4 q) {
    return vec4(-q.x, -q.y, -q.z, q.w);
}

vec4 quatFromAxis(float theta, vec3 v) {
    float s = sin(theta / 2);

    return vec4(s * v.x, s * v.y, s * v.z, cos(theta / 2));
}

vec4 quatMult (vec4 q, vec4 p) {
	return vec4(
		(q.w * p.x) + (q.x * p.w) + (q.y * p.z) - (q.z * p.y),
		(q.w * p.y) - (q.x * p.z) + (q.y * p.w) + (q.z * p.x),
		(q.w * p.z) + (q.x * p.y) - (q.y * p.x) + (q.z * p.w),
		(q.w * p.w) - (q.x * p.x) - (q.y * p.y) - (q.z * p.z)
	);
}

vec3 quatRotate(vec4 q, vec3 p, vec4 qc) {
	return quatMult(quatMult(q, vec4(p, 0)), qc).xyz;
}

vec3 quatRotate(vec4 q, vec3 p) {
	return quatMult(quatMult(q, vec4(p, 0)), quatConjugate(q)).xyz;
}


vec3 acc(float h2, vec3 pos) {
	//r^5 = (r^2)^2 * r = sqMag^2 * sqrt(sqMag)
	float r2 = sqMag(pos);
	float r5 = r2 * r2 * sqrt(r2);
	return -1.5*h2*pos/r5;
}

Ray rungekutta(float h2, Ray ray, float h) {
	vec3 k1, k2, k3, k4, l1, l2, l3, l4;

	k1 = ray.dir;
	l1 = acc(h2, ray.pos);

	k2 = ray.dir + h*0.5*l1;
	l2 = acc(h2, h*0.5*k1+ray.pos);

	k3 = ray.dir + h*0.5*l2;
	l3 = acc(h2, h*0.5*k2+ray.pos);

	k4 = ray.dir + h*l3;
	l4 = acc(h2, h*k3+ray.pos);

	return Ray(ray.pos+h/6*(k1+2*k2+2*k3+k4), ray.dir+h/6*(l1+2*l2+2*l3+l4));
	
}


void main() {
	uint index = gl_GlobalInvocationID.x;
	if (index >= TOTALCALLS) return; //bounds check for work group padding

	vec3 planeNormal = normalize(cross(-camPos, camDir));
	float angle = PI*index/TOTALCALLS;

	Ray ray = Ray(camPos, quatRotate(quatFromAxis(angle, planeNormal), -normalize(camPos)));

//	float x = float(index)/WIDTH -0.5;
//	x*= 2*WIDTH/HEIGHT;
//	float y = 0;
//
//	ray.dir = normalize(mat3(camRight, camUp, camDir) * vec3(x, y, 1));

	Ray prevRay = ray;
	rayPaths[index].pos[0] = ray.pos;
	rayPaths[index].dir[0] = ray.dir; 
	float h2 = sqMag(cross(ray.pos, ray.dir));
	float dt = float(100)/steps;//higher means less accurate, but further

	for (int i = 1; i < steps; i++) {
		prevRay = ray;
		ray=rungekutta(h2, prevRay, dt);
		if (sqMag(ray.pos)<=1) {//inside event horizon
			for (int j = i; j < steps; j++) {
				rayPaths[index].pos[j] = vec3(0);
				rayPaths[index].dir[j] = vec3(0);
				
			}
			return;
		}

		rayPaths[index].pos[i] = ray.pos;
		rayPaths[index].dir[i] = ray.dir;
		
				

		
	}
}

